services:
  - type: web
    name: subte-app-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist/frontend/browser
    plan: free
    envVars:
      - key: API_BASE_URL
        value: https://tu-backend-app.onrender.com/api